nama = input("Nama                 : ")
nim = input("NIM                  : ")
kelas = input("Kelas Paralel        : ")
ttl = input("Tempat/Tanggal Lahir : ")
alamat = input("Alamat               : ")
hobi = input("Hobby                : ")
nohp = input("No. HP               : ")
print("")
print(f"{'Nama':20s} : {nama}")
print(f"{'NIM':20s} : {nim}")
print(f"{'Kelas Paralel':20s} : {kelas}")
print(f"{'Tempat/Tanggal Lahir':20s} : {ttl}")
print(f"{'Alamat':20s} : {alamat}")
print(f"{'Hobby':20s} : {hobi}")
print(f"{'No. HP':20s} : {nohp}")